version: "3.6"
services:
  sut:
    image: aquasec/trivy:0.1.7
    volumes:
      - .:/projectroot
    working_dir: /projectroot
    environment:
      - SOURCE_BRANCH
      - SOURCE_COMMIT
      - COMMIT_MSG
      - DOCKER_REPO
      - DOCKERFILE_PATH
      - DOCKER_TAG
      - IMAGE_NAME
    command: --no-progress --exit-code 0 $DOCKER_REPO:$DOCKER_TAG