name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  security:
    name: "Security related jobs"
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    container:
      image: aquasec/trivy:latest
    steps:
      - name: "Vulnerability Scan Of Docker Images With Trivy"
        env: 
          DOCKER_REPO: freifunkhamm/mapshaper
          DOCKER_TAG: latest
        uses: docker://bash
        with:
          args: ls -al
