name: CI

on: 
  repository_dispatch:
    types: [my_custom_event]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      env:
        GITHUB_EVENT: ${{ toJson(github.event.client_payload) }}
      run: echo "$GITHUB_EVENT"
  security:
    name: "Security related jobs"
    runs-on: [ubuntu-latest]
    timeout-minutes: 30
    container:
      image: aquasec/trivy:latest
    steps:
      - name: "Checkout git repo"
        uses: actions/checkout@v1
      - name: "Show version (Trivy):"
        uses: docker://aquasec/trivy:latest
        with:
          args: -v
      - name: "Vulnerability Scan Of Docker Images With Trivy"
        uses: docker://aquasec/trivy:latest
        with:
          args: --format json --output report.json ${{ toJson(github.event.client_payload.repo) }}:${{ toJson(github.event.client_payload.tag) }}
      - name: "Show result (JSON):"
        run: cat report.json
        
